openapi: 3.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
paths:
  /topics:
    get:
      summary: searches unique topics
      operationId: topics
      description: |
        Return the value of unique topics
      responses:
        '200':
          description: topics
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: integer
        '400':
          description: bad input parameter

  /health:
    get:
      summary: health check
      operationId: health
      responses:
        '200':
          description: OK
        '503':
          description: KO
